# WORK IN PROGRESS. Do not use for now.

# Need to export as ENV var
# export TEST_DIR = tests
# export TEST_DATA = test_data
# export REQUIREMENTS_DIR = requirements
# PYLINT = flake8
# PYLINTFLAGS =
# PYTHONFILES = $(shell find source -name \*.py)
# PYTHONFILES += $(shell find tests -name \*.py)

# FORCE:

# lint:
# 	$(PYLINT) $(PYTHONFILES)

# pytests: $(PYTHONFILES)
# 	./pytests.sh

# tests: lint pytests

# prod: $(INCS) $(HTMLFILES) lint tests
# 	-git commit -a 
# 	git pull origin master
# 	git push origin master

# local: $(INCS) $(HTMLFILES) lint tests
# 	-git commit -a
# 	git pull origin master
# 	git push origin master